[package]
name = "headr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
anyhow = "1.0.79"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.0.4"
pretty_assertions = "1.4.0"
rand = "0.8.5"